services:
  postgres:
    image: postgres:14
    container_name: inflearn-clone-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inflearn_clone
    volumes:
      - inflearn_clone_volume:/var/lib/postgresql/data

volumes:
  inflearn_clone_volume:
